services:
  db:
    image: mysql:8
    container_name: swaglabs-db
    restart: always
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: swaglabs
      MYSQL_USER: swaguser
      MYSQL_PASSWORD: swagpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: swaglabs-pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: swaguser
      PMA_PASSWORD: swagpass

volumes:
  db_data:
