*** Variables ***
&{ACCOUNTS}
...                 standard_user=secret_sauce
...                 locked_out_user=secret_sauce
...                 problem_user=secret_sauce
...                 performance_glitch_user=secret_sauce
...                 error_user=secret_sauce
...                 visual_user=secret_sauce
...                 non_existing_user=secret_sauce

&{ACCOUNTS_STANDARD}
...                 standard_user=secret_sauce

&{ACCOUNTS_LOCKED}
...                 locked_out_user=secret_sauce

&{ACCOUNTS_PROBLEM}
...                 problem_user=secret_sauce

&{ACCOUNTS_PERF}
...                 performance_glitch_user=secret_sauce

&{ACCOUNTS_ERROR}
...                 error_user=secret_sauce

&{ACCOUNTS_VISUAL}
...                 visual_user=secret_sauce

&{ACCOUNTS_NON_EXIST}
...                 non_existing_user=secret_sauce
